### ISSUE TITLE
Audio-Only Mode

### ISSUE THREAD

**Issue by ksharizard** [unknownskl/xbox-xcloud-client#1033]
I only need the application to stream my xbox audio to my windows pc. Having both the video and the audio being streamed eats away at my internet unnecessarily. Can a toggle be added to the settings page to have an audio only mode?

**Comment by Jayian1890** [comment]
I believe the video gets sent regardless of rather you use it or not. But if this is possible, it'd be nice. My xbox controller died a few months after I bought it, and I've refused to waste money on another, so I've been using my trusty DS4 controller via remote play, that I've had since the dawn of the PS4. It still works perfectly. I simply turn the TV on and watch via that.

**Comment by unknownskl** [comment]
Added a toggle to disable the video. It is not possible afaik to disable the datastream because it gets sent anyway.
