### ISSUE TITLE
Controller input only support

### ISSUE THREAD

**Issue by boyinatree** [unknownskl/xbox-xcloud-client#1044]
Enhancement request:

Allow the screen to go dark after connecting to the Xbox and only turn it back on if you tap on the screen (or map a button to toggle screen on/off).

I use Greenlight as just a controller to play on the tv sometimes. This is just so I can get gyro aiming and auto fire on buttons. It is distracting to have the screen stay on.

**Comment by Kobi-Blade** [comment]
This would be extremely counter-productive, since most streamers been using Greenlight to run away from the official Xbox App due to doing exactly this (incl. myself and streamer friends to whom I recommended this alternative).

So please be very mindful on how you intent to implement this, the App is out of focus 75% of the time while streaming, and having the screen go dark or anything similar would ruin the entire experience.
