### ISSUE TITLE
Steam Deck: Quit game error 410

### ISSUE THREAD

**Issue by Geier97332** [unknownskl/xbox-xcloud-client#742]
Hi,
I use latest beta 3 on my Steam Deck only for XBox Cloud Gaming.
Everything is running fine, except of quitting the game.
When I want to quit the game in the Menu I get a message "Something went wrong" and the message "Error in Promise: {"status":410}.

![PXL_20230217_102339430.jpg](https://user-images.githubusercontent.com/95997878/219619759-b9e3a071-6bb0-4f35-88eb-59f443518604.jpg)

**Comment by unknownskl** [comment]
This is a known bug indeed (to me at least). The last version fixed some UI glitches when receiving an error while provisioning the stream and the fix for that introduced this bug.
The application is trying to send a keepalive request while the stream has ended. It is safe to press ok here and go back manually using the top bar navigation
