### ISSUE TITLE
Beta 6 won’t connect to console

### ISSUE THREAD

**Issue by lasagneking** [unknownskl/xbox-xcloud-client#798]
Had to reinstall my operating system (Steam Deck) so needed to set this up once again.

Downloaded and installed beta 6, initial sign in to Xbox hangs forever, once I quit the app and reload, it appears to be signed in, my console is listed.

xcloud games load and work perfectly however when. Trying to connect to my console I get the error:-

Error in Promise: {"state":"Failed","detailedSessionState": 0,"errorDetails":{"code":"WNSError","message":"Xccs: ErrorCallingWNS: Send command failed: State Waiting ForServerToRegister"}}

**Comment by eahlys** [comment]
Experiencing the same issue here on beta2. Updated to beta6, same issue.

**Comment by unknownskl** [comment]
The error means that the Xbox is not able to retrieve the streaming start command and is waiting for the Xbox to register with the Xbox API. This is mostly fixed by restarting the console or by trying to start the stream again. Sometimes it will work for the second time but for some people it doesn't. This is not something we can fix as the error comes from the Xbox API's.

I will try to give it a better error description with some tips to fix the error.

**Comment by unknownskl** [comment]
v2.0.0-beta7 just released and includes a better error description for this specific error.
