### ISSUE TITLE
Major Issues on MAC High Sierra 10.13 - ALL BETAS

### ISSUE THREAD

**Issue by ExcelsiorGamingYT** [unknownskl/xbox-xcloud-client#899]
Hello i did open a case a few days ago but my issues are now escalating!! Firstly this was all working fine until the other day i have been running beta 2 with no issues at all. Then the other day went to login in and it wouldn't login at all and a "this page could not be found" box was just sitting there and its still like it today. So i decided to see if any other version of Greenlight would work but Betas 1-4 all have this same issues and Betas 5-10 i just get a constant error box at startup i have included some photos below of my issues.

Thanks
![Beta 1-4 Login Issue](https://github.com/unknownskl/greenlight/assets/140591650/dd21fa92-df3c-411e-a345-02321f62e2e4)
![Beta 5-8 Error](https://github.com/unknownskl/greenlight/assets/140591650/e7159322-0e3a-419a-b2bc-28a4a86575a2)
![Beta 9-10 Error](https://github.com/unknownskl/greenlight/assets/140591650/908c6fd9-0896-4a6d-9972-2b9c961b2bfd)

**Comment by unknownskl** [comment]
High sierra is EOL since end 2020. It is possible that some dependencies are not compatible anymore with High Sierra.
Are you able to update your Mac OS version to a supported version?

**Comment by ExcelsiorGamingYT** [comment]
> High sierra is EOL since end 2020. It is possible that some dependencies are not compatible anymore with High Sierra. Are you able to update your Mac OS version to a supported version?

No my mac is to old, it was all working fine until Friday

**Comment by Pommmmes** [comment]
Hi,
i had the same problem on high sierra, i deleted application support-greenlight in user library , installed beta 4 and it is working...

**Comment by ExcelsiorGamingYT** [comment]
> Hi, i had the same problem on high sierra, i deleted application support-greenlight in user library , installed beta 4 and it is working...

Your a legend thankyou!!!!

**Comment by NoCodeLeftBehind** [comment]
Thanks for your hard work on Greenlight! I am commenting to add that this issue is not limited to Mac OS. I am getting it on Windows 11 as well. Beta 4 is the last working version for me. At launch, newer versions give similar errors as in the screenshots posted by the Mac user above.

Beta 5 error on Windows:
![image](https://github.com/unknownskl/greenlight/assets/11912638/3e4567a6-c536-47e0-b053-0cb180ac8424)

Beta 11 error on Windows:
![image](https://github.com/unknownskl/greenlight/assets/11912638/e031dca8-a878-4d98-b665-c293c2345381)

Based on the error messages and fact that the problem started in Beta 5, which added the new XAL Authentication module, it seems something is going wrong with that module is some circumstances on multiple platforms. Hope this helps sort out a fix.

**Comment by NoCodeLeftBehind** [comment]
To follow up to my previous post, I did some searching around for node-loader errors for other projects and found this:

https://github.com/decred/decrediton/issues/3674

I can confirm the fix suggested there (installing the VC++ 14 Redist using “winget install Microsoft.VCRedist.2015+.x64” at a command prompt) worked on Windows 11. Not sure how Mac folks install that.

**Comment by unknownskl** [comment]
Please try the new 2.0.0-beta15 version. It should hopefully fix all the dependency errors.

**Comment by Pommmmes** [comment]
Thank you so much,works perfectly here:-)Best RegardsThomas SaweraSent from my mobile device On Nov 28, 2023, at 01:21, UnknownSKL ***@***.***> wrote:﻿
Please try the new 2.0.0-beta15 version. It should hopefully fix all the dependency errors.
