### ISSUE TITLE
[Request] force Bitrate option

### ISSUE THREAD

**Issue by darwpm4gs** [unknownskl/xbox-xcloud-client#96]
like in old xbox app
https://www.reddit.com/r/xboxone/comments/8ca0bl/xbox_app_increasing_streaming_quality_beyond_very/

**Comment by TheWorldlyGamer** [comment]
Yeah this would be great. I'm finding it quite blurry and grainy to look at when using this app.

**Comment by unknownskl** [comment]
Unfortunately setting the bitrate is not supported in xCloud. Maybe they will in the future.

**Comment by unknownskl** [comment]
Try out the new beta3 release. It should have an improved bitrate :)

**Comment by chosafine** [comment]
Hi,

Is there a way to manually specify resolution / bitrate for home console (not xcloud, but specifically to a local xbox series console) streaming?

Compared to the Windows 11 Xbox application it appears the resolution is lower (this may be just a bitrate difference, I am not 100% sure) when using this app. 

Absolutely love the work you're doing here! Just am curious if there is a way (either via the console or by changing some parameters in code) to force a higher bit rate and/or a 1080p stream.

Thank you

**Comment by unknownskl** [comment]
The v2.0.0-beta1 client has a bitrate switcher now. The resolution and bitrate is currently limited to 720p 30fps because of the codec. The xbox app on the pc also uses a different way of streaming. This application uses WebRTC for the stream while the xbox pc app uses a custom UDP protocol. (Which is being worked on too, but don't expect anything within half a year / a year from now)
