### ISSUE TITLE
Microsoft Sign-in

### ISSUE THREAD

**Issue by LordJulius** [unknownskl/xbox-xcloud-client#990]
I cant sign into Microsoft. It shows up for a brief second and then turns white. 
![Screenshot_20231010_085821](https://github.com/unknownskl/greenlight/assets/34140234/376ea94d-ca63-49d4-a862-a27b9dbd2052)

**Comment by MANICX100** [comment]
Updating the electron webview from v21 to v26 has made things to screwy please use
https://github.com/unknownskl/greenlight/releases/tag/v2.0.0-beta12
Instead for now

**Comment by MANICX100** [comment]
Linux specific issue confirmed

**Comment by LeChatP** [comment]
https://community.frame.work/t/electron-apps-are-blank-empty-on-startup-solvable/23574
this maybe ?

**Comment by maciej-c** [comment]
I can confirm this exact issue on Fedora 38 (Gnome)

**Comment by RobLW** [comment]
Using on arch (cachyOS) and also find the screen blanks out. This doesn't appear to happen if for example you load Greenlight and don't focus on the window. But as soon as mouse moves over or your focus the window it goes all white within 20 seconds.
If you are bloody fast you can successfully login but the issue still happens on the main dashboard.

I do not have Xf86-video-intel driver installed on my system, so the removal of this (suggested in the link from @LeChatP ) doesn't help out here. 

Unfortunately I do think the problem is more "electron" rather than "greenlight".

**Comment by LeChatP** [comment]
Fixed since a month for me, Maybe electron or microsoft fixed a buggy dark dependency. Tested for 2.0.0-beta12 and 2.0.1, both fixed... Who knows.
Or maybe its since i've upgraded to ubuntu23.04... Nevermind, it works for me.

**Comment by unknownskl** [comment]
This bug should be solved in the 2.0.1 release. Please reopen the issue if the problem persists.
